# Generated by Django 5.2.13 on 2026-04-09 22:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('glosa', models.TextField(blank=True)),
                ('origen_tipo', models.CharField(blank=True, max_length=50)),
                ('origen_id', models.BigIntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ComunicacionBaja',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('referencia_tipo', models.CharField(blank=True, max_length=50)),
                ('referencia_id', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.CharField(default='REGISTRADO', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_baja', to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PlanCuenta',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=30)),
                ('es_activo', models.BooleanField(default=False, help_text='Marcar si representa un activo fijo / cuenta de activo.')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cuentas', to='core.empresa')),
            ],
            options={
                'verbose_name_plural': 'Plan de cuentas',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='AsientoLinea',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_asiento', to='contabilidad.plancuenta')),
            ],
        ),
    ]
