# Generated by Django 5.2.13 on 2026-04-12 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vendedor_y_comprobante_campos'),
        ('ventas', '0003_documentoventa_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoventa',
            name='condicion_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('DEPOSITO_CUENTA', 'Depósito en cuenta'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('TARJETA_DEBITO', 'Tarjeta de débito'), ('OTROS', 'Otros medios de pago'), ('TARJETA_CREDITO', 'Tarjeta de crédito'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='moneda',
            field=models.CharField(choices=[('PEN', 'PEN (S/)'), ('USD', 'USD ($)')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='precio_incluye_igv',
            field=models.BooleanField(default=False, help_text='Si es True, el precio unitario capturado en UI incluye IGV; se almacena línea sin IGV.'),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='tipo_operacion',
            field=models.CharField(choices=[('VENTA_INTERNA', 'Venta interna'), ('ANTICIPO', 'Anticipo'), ('REGULARIZACION_ANTICIPO', 'Regularización de anticipo'), ('EXPORTACION', 'Exportación'), ('NO_DOMICILIADOS', 'No domiciliados'), ('VENTA_ITINERANTE', 'Venta itinerante')], default='VENTA_INTERNA', max_length=40),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_venta', to='core.vendedor'),
        ),
    ]
