# Generated by Django 5.2.13 on 2026-04-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_vendedor_y_comprobante_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoventa',
            name='nubefact_sunat_codigo',
            field=models.CharField(blank=True, default='', help_text='Código de respuesta SUNAT devuelto por Nubefact (p. ej. sunat_responsecode).', max_length=32),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='nubefact_sunat_descripcion',
            field=models.TextField(blank=True, default='', help_text='Mensaje / descripción SUNAT devuelta por Nubefact (p. ej. sunat_description).'),
        ),
    ]
