# Generated by Django 5.2.13 on 2026-04-12 02:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vendedor_y_comprobante_campos'),
        ('ventas', '0005_documento_sunat_nubefact'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='condicion_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='correlativo',
            field=models.PositiveIntegerField(blank=True, help_text='Número secuencial interno por empresa+serie al emitir la cotización.', null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('DEPOSITO_CUENTA', 'Depósito en cuenta'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('TARJETA_DEBITO', 'Tarjeta de débito'), ('OTROS', 'Otros medios de pago'), ('TARJETA_CREDITO', 'Tarjeta de crédito'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='moneda',
            field=models.CharField(choices=[('PEN', 'PEN (S/)'), ('USD', 'USD ($)')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='precio_incluye_igv',
            field=models.BooleanField(default=False, help_text='Si es True, el precio unitario en UI incluye IGV; se almacena línea sin IGV.'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='serie',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_operacion',
            field=models.CharField(choices=[('VENTA_INTERNA', 'Venta interna'), ('ANTICIPO', 'Anticipo'), ('REGULARIZACION_ANTICIPO', 'Regularización de anticipo'), ('EXPORTACION', 'Exportación'), ('NO_DOMICILIADOS', 'No domiciliados'), ('VENTA_ITINERANTE', 'Venta itinerante')], default='VENTA_INTERNA', max_length=40),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='core.vendedor'),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='cotizacion_origen',
            field=models.OneToOneField(blank=True, help_text='Si se generó este borrador desde una cotización interna emitida.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_convertido', to='ventas.cotizacion'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(condition=models.Q(('correlativo__isnull', False), models.Q(('serie', ''), _negated=True)), fields=('empresa', 'serie', 'correlativo'), name='uniq_cotizacion_correlativo'),
        ),
    ]
