# Generated by Django 5.2.13 on 2026-04-12 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_almacen_activo'),
        ('ventas', '0006_cotizacion_interna_y_origen_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoventa',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Almacén del movimiento de inventario al emitir (salida en F/B/NV; ingreso en NCC).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_venta', to='inventario.almacen'),
        ),
    ]
