-- Fragmento fuente (sin bootstrap core). Archivo único recomendado:
--   docs/sql/gestor_ventas_esquema_completo.sql
-- Regenerar el unificado: python scripts/merge_schema_sql.py
--
-- Motor al generar sqlmigrate: SQLite si no hay DATABASE_URL.

-- === contenttypes.0001_initial ===
BEGIN;
--
-- Create model ContentType
--
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
--
-- Alter unique_together for contenttype (1 constraint(s))
--
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");
COMMIT;

-- === auth.0001_initial ===
BEGIN;
--
-- Create model Permission
--
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
--
-- Create model Group
--
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model User
--
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NOT NULL, "is_superuser" boolean NOT NULL, "username" varchar(30) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "email" varchar(75) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL);
CREATE TABLE "auth_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "auth_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "permission_id" integer NOT NULL);
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_user_username_6821ab7c_like" ON "auth_user" ("username" varchar_pattern_ops);
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
COMMIT;

-- === admin.0001_initial ===
BEGIN;
--
-- Create model LogEntry
--
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" integer NOT NULL);
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
COMMIT;

-- === admin.0002_logentry_remove_auto_add ===
BEGIN;
--
-- Alter field action_time on logentry
--
-- (no-op)
COMMIT;

-- === admin.0003_logentry_add_action_flag_choices ===
BEGIN;
--
-- Alter field action_flag on logentry
--
-- (no-op)
COMMIT;

-- === core.0001_initial ===
BEGIN;
--
-- Custom state/database change combination
--
-- (no-op)
COMMIT;

-- === administracion.0001_initial ===
BEGIN;
--
-- Create model Tarea
--
CREATE TABLE "administracion_tarea" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "titulo" varchar(255) NOT NULL, "descripcion" text NOT NULL, "completada" boolean NOT NULL, "fecha_limite" date NULL, "modulo" varchar(40) NOT NULL, "usuario_id" integer NOT NULL);
--
-- Create model ConfiguracionSistema
--
CREATE TABLE "administracion_configuracionsistema" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "clave" varchar(100) NOT NULL, "valor" jsonb NOT NULL, "empresa_id" bigint NOT NULL);
ALTER TABLE "administracion_tarea" ADD CONSTRAINT "administracion_tarea_usuario_id_ada7fb5a_fk_auth_user_id" FOREIGN KEY ("usuario_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "administracion_tarea_usuario_id_ada7fb5a" ON "administracion_tarea" ("usuario_id");
ALTER TABLE "administracion_configuracionsistema" ADD CONSTRAINT "administracion_configura_empresa_id_clave_afa48922_uniq" UNIQUE ("empresa_id", "clave");
ALTER TABLE "administracion_configuracionsistema" ADD CONSTRAINT "administracion_confi_empresa_id_a6733658_fk_empresa_i" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "administracion_configuracionsistema_clave_55badee6" ON "administracion_configuracionsistema" ("clave");
CREATE INDEX "administracion_configuracionsistema_clave_55badee6_like" ON "administracion_configuracionsistema" ("clave" varchar_pattern_ops);
CREATE INDEX "administracion_configuracionsistema_empresa_id_a6733658" ON "administracion_configuracionsistema" ("empresa_id");
COMMIT;

-- === contenttypes.0002_remove_content_type_name ===
BEGIN;
--
-- Change Meta options on contenttype
--
-- (no-op)
--
-- Alter field name on contenttype
--
ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field name from contenttype
--
ALTER TABLE "django_content_type" DROP COLUMN "name" CASCADE;
COMMIT;

-- === auth.0002_alter_permission_name_max_length ===
BEGIN;
--
-- Alter field name on permission
--
ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255);
COMMIT;

-- === auth.0003_alter_user_email_max_length ===
BEGIN;
--
-- Alter field email on user
--
ALTER TABLE "auth_user" ALTER COLUMN "email" TYPE varchar(254);
COMMIT;

-- === auth.0004_alter_user_username_opts ===
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- === auth.0005_alter_user_last_login_null ===
BEGIN;
--
-- Alter field last_login on user
--
ALTER TABLE "auth_user" ALTER COLUMN "last_login" DROP NOT NULL;
COMMIT;

-- === auth.0006_require_contenttypes_0002 ===
BEGIN;
-- (no SQL operations)
COMMIT;

-- === auth.0007_alter_validators_add_error_messages ===
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- === auth.0008_alter_user_username_max_length ===
BEGIN;
--
-- Alter field username on user
--
ALTER TABLE "auth_user" ALTER COLUMN "username" TYPE varchar(150);
COMMIT;

-- === auth.0009_alter_user_last_name_max_length ===
BEGIN;
--
-- Alter field last_name on user
--
ALTER TABLE "auth_user" ALTER COLUMN "last_name" TYPE varchar(150);
COMMIT;

-- === auth.0010_alter_group_name_max_length ===
BEGIN;
--
-- Alter field name on group
--
ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150);
COMMIT;

-- === auth.0011_update_proxy_permissions ===
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- === auth.0012_alter_user_first_name_max_length ===
BEGIN;
--
-- Alter field first_name on user
--
ALTER TABLE "auth_user" ALTER COLUMN "first_name" TYPE varchar(150);
COMMIT;

-- === authtoken.0001_initial ===
BEGIN;
--
-- Create model Token
--
CREATE TABLE "authtoken_token" ("key" varchar(40) NOT NULL PRIMARY KEY, "created" timestamp with time zone NOT NULL, "user_id" integer NOT NULL UNIQUE);
ALTER TABLE "authtoken_token" ADD CONSTRAINT "authtoken_token_user_id_35299eff_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "authtoken_token_key_10f0b77e_like" ON "authtoken_token" ("key" varchar_pattern_ops);
COMMIT;

-- === authtoken.0002_auto_20160226_1747 ===
BEGIN;
--
-- Change Meta options on token
--
-- (no-op)
--
-- Alter field created on token
--
-- (no-op)
--
-- Alter field key on token
--
-- (no-op)
--
-- Alter field user on token
--
-- (no-op)
COMMIT;

-- === authtoken.0003_tokenproxy ===
BEGIN;
--
-- Create proxy model TokenProxy
--
-- (no-op)
COMMIT;

-- === authtoken.0004_alter_tokenproxy_options ===
BEGIN;
--
-- Change Meta options on tokenproxy
--
-- (no-op)
COMMIT;

-- === inventario.0001_initial ===
BEGIN;
--
-- Create model Almacen
--
CREATE TABLE "inventario_almacen" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar(120) NOT NULL, "es_principal" boolean NOT NULL, "sucursal_id" bigint NOT NULL);
--
-- Create model Atributo
--
CREATE TABLE "inventario_atributo" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar(80) NOT NULL, "empresa_id" bigint NOT NULL);
--
-- Create model Categoria
--
CREATE TABLE "inventario_categoria" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar(120) NOT NULL, "empresa_id" bigint NOT NULL, "padre_id" bigint NULL);
--
-- Create model Item
--
CREATE TABLE "inventario_item" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "codigo" varchar(50) NOT NULL, "nombre" varchar(255) NOT NULL, "unidad_medida" varchar(20) NOT NULL, "es_servicio" boolean NOT NULL, "activo" boolean NOT NULL, "categoria_id" bigint NULL, "empresa_id" bigint NOT NULL);
--
-- Create model ItemAtributoValor
--
CREATE TABLE "inventario_itematributovalor" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "valor" varchar(255) NOT NULL, "atributo_id" bigint NOT NULL, "item_id" bigint NOT NULL);
--
-- Create model ListaPrecio
--
CREATE TABLE "inventario_listaprecio" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar(120) NOT NULL, "moneda" varchar(3) NOT NULL, "activa" boolean NOT NULL, "empresa_id" bigint NOT NULL);
--
-- Create model ListaPrecioItem
--
CREATE TABLE "inventario_listaprecioitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "precio" numeric(18, 4) NOT NULL, "item_id" bigint NOT NULL, "lista_id" bigint NOT NULL);
--
-- Create model MovimientoStock
--
CREATE TABLE "inventario_movimientostock" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "tipo" varchar(20) NOT NULL, "referencia_tipo" varchar(50) NOT NULL, "referencia_id" bigint NULL, "glosa" varchar(255) NOT NULL, "almacen_id" bigint NOT NULL, "empresa_id" bigint NOT NULL, "usuario_id" integer NULL);
--
-- Create model MovimientoStockLinea
--
CREATE TABLE "inventario_movimientostocklinea" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "cantidad" numeric(18, 4) NOT NULL, "item_id" bigint NOT NULL, "movimiento_id" bigint NOT NULL);
--
-- Create model Stock
--
CREATE TABLE "inventario_stock" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "cantidad" numeric(18, 4) NOT NULL, "almacen_id" bigint NOT NULL, "item_id" bigint NOT NULL);
--
-- Create constraint uniq_item_codigo_por_empresa on model item
--
CREATE UNIQUE INDEX "uniq_item_codigo_por_empresa" ON "inventario_item" ("empresa_id", "codigo") WHERE NOT ("codigo" = '');
--
-- Alter unique_together for itematributovalor (1 constraint(s))
--
ALTER TABLE "inventario_itematributovalor" ADD CONSTRAINT "inventario_itematributovalor_item_id_atributo_id_e0c9e62b_uniq" UNIQUE ("item_id", "atributo_id");
--
-- Alter unique_together for listaprecioitem (1 constraint(s))
--
ALTER TABLE "inventario_listaprecioitem" ADD CONSTRAINT "inventario_listaprecioitem_lista_id_item_id_6018225e_uniq" UNIQUE ("lista_id", "item_id");
--
-- Alter unique_together for stock (1 constraint(s))
--
ALTER TABLE "inventario_stock" ADD CONSTRAINT "inventario_stock_item_id_almacen_id_a582995f_uniq" UNIQUE ("item_id", "almacen_id");
ALTER TABLE "inventario_almacen" ADD CONSTRAINT "inventario_almacen_sucursal_id_48b4d86d_fk_sucursal_id" FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventario_almacen_sucursal_id_48b4d86d" ON "inventario_almacen" ("sucursal_id");
ALTER TABLE "inventario_atributo" ADD CONSTRAINT "inventario_atributo_empresa_id_1689a517_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventario_atributo_empresa_id_1689a517" ON "inventario_atributo" ("empresa_id");
ALTER TABLE "inventario_categoria" ADD CONSTRAINT "inventario_categoria_empresa_id_cf224431_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inventario_categoria" ADD CONSTRAINT "inventario_categoria_padre_id_4835214c_fk_inventari" FOREIGN KEY ("padre_id") REFERENCES "inventario_categoria" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventario_categoria_empresa_id_cf224431" ON "inventario_categoria" ("empresa_id");
CREATE INDEX "inventario_categoria_padre_id_4835214c" ON "inventario_categoria" ("padre_id");
ALTER TABLE "inventario_item" ADD CONSTRAINT "inventario_item_categoria_id_6d59f8f5_fk_inventari" FOREIGN KEY ("categoria_id") REFERENCES "inventario_categoria" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inventario_item" ADD CONSTRAINT "inventario_item_empresa_id_f0394fa4_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventario_item_codigo_e23213ef" ON "inventario_item" ("codigo");
CREATE INDEX "inventario_item_codigo_e23213ef_like" ON "inventario_item" ("codigo" varchar_pattern_ops);
CREATE INDEX "inventario_item_categoria_id_6d59f8f5" ON "inventario_item" ("categoria_id");
CREATE INDEX "inventario_item_empresa_id_f0394fa4" ON "inventario_item" ("empresa_id");
ALTER TABLE "inventario_itematributovalor" ADD CONSTRAINT "inventario_itematrib_atributo_id_72ac618b_fk_inventari" FOREIGN KEY ("atributo_id") REFERENCES "inventario_atributo" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inventario_itematributovalor" ADD CONSTRAINT "inventario_itematrib_item_id_df2cfbae_fk_inventari" FOREIGN KEY ("item_id") REFERENCES "inventario_item" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventario_itematributovalor_atributo_id_72ac618b" ON "inventario_itematributovalor" ("atributo_id");
CREATE INDEX "inventario_itematributovalor_item_id_df2cfbae" ON "inventario_itematributovalor" ("item_id");
ALTER TABLE "inventario_listaprecio" ADD CONSTRAINT "inventario_listaprecio_empresa_id_6fc594d8_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventario_listaprecio_empresa_id_6fc594d8" ON "inventario_listaprecio" ("empresa_id");
ALTER TABLE "inventario_listaprecioitem" ADD CONSTRAINT "inventario_listaprec_item_id_65b112c7_fk_inventari" FOREIGN KEY ("item_id") REFERENCES "inventario_item" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inventario_listaprecioitem" ADD CONSTRAINT "inventario_listaprec_lista_id_f087223e_fk_inventari" FOREIGN KEY ("lista_id") REFERENCES "inventario_listaprecio" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventario_listaprecioitem_item_id_65b112c7" ON "inventario_listaprecioitem" ("item_id");
CREATE INDEX "inventario_listaprecioitem_lista_id_f087223e" ON "inventario_listaprecioitem" ("lista_id");
ALTER TABLE "inventario_movimientostock" ADD CONSTRAINT "inventario_movimient_almacen_id_a63e2ced_fk_inventari" FOREIGN KEY ("almacen_id") REFERENCES "inventario_almacen" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inventario_movimientostock" ADD CONSTRAINT "inventario_movimientostock_empresa_id_474412b5_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inventario_movimientostock" ADD CONSTRAINT "inventario_movimientostock_usuario_id_80ad7867_fk_auth_user_id" FOREIGN KEY ("usuario_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventario_movimientostock_almacen_id_a63e2ced" ON "inventario_movimientostock" ("almacen_id");
CREATE INDEX "inventario_movimientostock_empresa_id_474412b5" ON "inventario_movimientostock" ("empresa_id");
CREATE INDEX "inventario_movimientostock_usuario_id_80ad7867" ON "inventario_movimientostock" ("usuario_id");
ALTER TABLE "inventario_movimientostocklinea" ADD CONSTRAINT "inventario_movimient_item_id_1146c460_fk_inventari" FOREIGN KEY ("item_id") REFERENCES "inventario_item" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inventario_movimientostocklinea" ADD CONSTRAINT "inventario_movimient_movimiento_id_8dcbeb1d_fk_inventari" FOREIGN KEY ("movimiento_id") REFERENCES "inventario_movimientostock" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventario_movimientostocklinea_item_id_1146c460" ON "inventario_movimientostocklinea" ("item_id");
CREATE INDEX "inventario_movimientostocklinea_movimiento_id_8dcbeb1d" ON "inventario_movimientostocklinea" ("movimiento_id");
ALTER TABLE "inventario_stock" ADD CONSTRAINT "inventario_stock_almacen_id_c3ed995d_fk_inventario_almacen_id" FOREIGN KEY ("almacen_id") REFERENCES "inventario_almacen" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inventario_stock" ADD CONSTRAINT "inventario_stock_item_id_92d38efa_fk_inventario_item_id" FOREIGN KEY ("item_id") REFERENCES "inventario_item" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventario_stock_almacen_id_c3ed995d" ON "inventario_stock" ("almacen_id");
CREATE INDEX "inventario_stock_item_id_92d38efa" ON "inventario_stock" ("item_id");
COMMIT;

-- === compras.0001_initial ===
BEGIN;
--
-- Create model DocumentoCompra
--
CREATE TABLE "compras_documentocompra" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "tipo" varchar(30) NOT NULL, "serie" varchar(10) NOT NULL, "numero" varchar(20) NOT NULL, "fecha" date NOT NULL, "estado" varchar(20) NOT NULL, "total" numeric(18, 2) NOT NULL, "es_electronica" boolean NOT NULL, "hash_xml" varchar(64) NOT NULL, "ruta_archivo" varchar(512) NOT NULL, "empresa_id" bigint NOT NULL, "proveedor_id" bigint NOT NULL);
--
-- Create model DocumentoCompraLinea
--
CREATE TABLE "compras_documentocompralinea" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "cantidad" numeric(18, 4) NOT NULL, "precio_unit" numeric(18, 4) NOT NULL, "subtotal" numeric(18, 2) NOT NULL, "documento_id" bigint NOT NULL, "item_id" bigint NOT NULL);
--
-- Create model GastoRecurrente
--
CREATE TABLE "compras_gastorecurrente" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "concepto" varchar(255) NOT NULL, "monto" numeric(18, 2) NOT NULL, "periodicidad" varchar(20) NOT NULL, "dia_ejecucion" smallint NULL CHECK ("dia_ejecucion" >= 0), "activo" boolean NOT NULL, "proxima_fecha" date NULL, "empresa_id" bigint NOT NULL);
--
-- Create model OrdenCompra
--
CREATE TABLE "compras_ordencompra" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "numero" varchar(30) NOT NULL, "fecha" date NOT NULL, "estado" varchar(20) NOT NULL, "total" numeric(18, 2) NOT NULL, "empresa_id" bigint NOT NULL, "proveedor_id" bigint NOT NULL);
--
-- Create model OrdenCompraLinea
--
CREATE TABLE "compras_ordencompralinea" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "cantidad" numeric(18, 4) NOT NULL, "precio_unit" numeric(18, 4) NOT NULL, "item_id" bigint NOT NULL, "orden_id" bigint NOT NULL);
ALTER TABLE "compras_documentocompra" ADD CONSTRAINT "compras_documentocompra_empresa_id_708d8e31_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "compras_documentocompra" ADD CONSTRAINT "compras_documentocompra_proveedor_id_61a1a6e9_fk_proveedor_id" FOREIGN KEY ("proveedor_id") REFERENCES "proveedor" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "compras_documentocompra_empresa_id_708d8e31" ON "compras_documentocompra" ("empresa_id");
CREATE INDEX "compras_documentocompra_proveedor_id_61a1a6e9" ON "compras_documentocompra" ("proveedor_id");
ALTER TABLE "compras_documentocompralinea" ADD CONSTRAINT "compras_documentocom_documento_id_558ec5d1_fk_compras_d" FOREIGN KEY ("documento_id") REFERENCES "compras_documentocompra" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "compras_documentocompralinea" ADD CONSTRAINT "compras_documentocom_item_id_6fb5c4df_fk_inventari" FOREIGN KEY ("item_id") REFERENCES "inventario_item" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "compras_documentocompralinea_documento_id_558ec5d1" ON "compras_documentocompralinea" ("documento_id");
CREATE INDEX "compras_documentocompralinea_item_id_6fb5c4df" ON "compras_documentocompralinea" ("item_id");
ALTER TABLE "compras_gastorecurrente" ADD CONSTRAINT "compras_gastorecurrente_empresa_id_6d61d5ac_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "compras_gastorecurrente_empresa_id_6d61d5ac" ON "compras_gastorecurrente" ("empresa_id");
ALTER TABLE "compras_ordencompra" ADD CONSTRAINT "compras_ordencompra_empresa_id_5c4630d8_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "compras_ordencompra" ADD CONSTRAINT "compras_ordencompra_proveedor_id_c42e35e1_fk_proveedor_id" FOREIGN KEY ("proveedor_id") REFERENCES "proveedor" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "compras_ordencompra_empresa_id_5c4630d8" ON "compras_ordencompra" ("empresa_id");
CREATE INDEX "compras_ordencompra_proveedor_id_c42e35e1" ON "compras_ordencompra" ("proveedor_id");
ALTER TABLE "compras_ordencompralinea" ADD CONSTRAINT "compras_ordencompralinea_item_id_f5822a4b_fk_inventario_item_id" FOREIGN KEY ("item_id") REFERENCES "inventario_item" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "compras_ordencompralinea" ADD CONSTRAINT "compras_ordencompral_orden_id_e4e2eec7_fk_compras_o" FOREIGN KEY ("orden_id") REFERENCES "compras_ordencompra" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "compras_ordencompralinea_item_id_f5822a4b" ON "compras_ordencompralinea" ("item_id");
CREATE INDEX "compras_ordencompralinea_orden_id_e4e2eec7" ON "compras_ordencompralinea" ("orden_id");
COMMIT;

-- === compras.0002_condicion_pago_tesoreria ===
BEGIN;
--
-- Add field condicion_pago to documentocompra
--
ALTER TABLE "compras_documentocompra" ADD COLUMN "condicion_pago" varchar(10) DEFAULT 'CONTADO' NOT NULL;
ALTER TABLE "compras_documentocompra" ALTER COLUMN "condicion_pago" DROP DEFAULT;
--
-- Add field fecha_vencimiento to documentocompra
--
ALTER TABLE "compras_documentocompra" ADD COLUMN "fecha_vencimiento" date NULL;
COMMIT;

-- === compras.0003_documento_compra_subtotal_igv ===
BEGIN;
--
-- Add field subtotal to documentocompra
--
ALTER TABLE "compras_documentocompra" ADD COLUMN "subtotal" numeric(18, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "compras_documentocompra" ALTER COLUMN "subtotal" DROP DEFAULT;
--
-- Add field igv to documentocompra
--
ALTER TABLE "compras_documentocompra" ADD COLUMN "igv" numeric(18, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "compras_documentocompra" ALTER COLUMN "igv" DROP DEFAULT;
--
-- Add field precio_incluye_igv to documentocompra
--
ALTER TABLE "compras_documentocompra" ADD COLUMN "precio_incluye_igv" boolean DEFAULT false NOT NULL;
ALTER TABLE "compras_documentocompra" ALTER COLUMN "precio_incluye_igv" DROP DEFAULT;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- === contabilidad.0001_initial ===
BEGIN;
--
-- Create model AsientoContable
--
CREATE TABLE "contabilidad_asientocontable" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "fecha" date NOT NULL, "glosa" text NOT NULL, "origen_tipo" varchar(50) NOT NULL, "origen_id" bigint NULL, "empresa_id" bigint NOT NULL);
--
-- Create model ComunicacionBaja
--
CREATE TABLE "contabilidad_comunicacionbaja" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "fecha" date NOT NULL, "descripcion" text NOT NULL, "referencia_tipo" varchar(50) NOT NULL, "referencia_id" bigint NULL, "estado" varchar(20) NOT NULL, "empresa_id" bigint NOT NULL);
--
-- Create model PlanCuenta
--
CREATE TABLE "contabilidad_plancuenta" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "codigo" varchar(20) NOT NULL, "nombre" varchar(255) NOT NULL, "tipo" varchar(30) NOT NULL, "es_activo" boolean NOT NULL, "activo" boolean NOT NULL, "empresa_id" bigint NOT NULL);
--
-- Create model AsientoLinea
--
CREATE TABLE "contabilidad_asientolinea" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "debe" numeric(18, 2) NOT NULL, "haber" numeric(18, 2) NOT NULL, "asiento_id" bigint NOT NULL, "cuenta_id" bigint NOT NULL);
ALTER TABLE "contabilidad_asientocontable" ADD CONSTRAINT "contabilidad_asientocontable_empresa_id_9f9b527f_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "contabilidad_asientocontable_empresa_id_9f9b527f" ON "contabilidad_asientocontable" ("empresa_id");
ALTER TABLE "contabilidad_comunicacionbaja" ADD CONSTRAINT "contabilidad_comunicacionbaja_empresa_id_80fae785_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "contabilidad_comunicacionbaja_empresa_id_80fae785" ON "contabilidad_comunicacionbaja" ("empresa_id");
ALTER TABLE "contabilidad_plancuenta" ADD CONSTRAINT "contabilidad_plancuenta_empresa_id_codigo_9383101f_uniq" UNIQUE ("empresa_id", "codigo");
ALTER TABLE "contabilidad_plancuenta" ADD CONSTRAINT "contabilidad_plancuenta_empresa_id_57322b76_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "contabilidad_plancuenta_codigo_9313916b" ON "contabilidad_plancuenta" ("codigo");
CREATE INDEX "contabilidad_plancuenta_codigo_9313916b_like" ON "contabilidad_plancuenta" ("codigo" varchar_pattern_ops);
CREATE INDEX "contabilidad_plancuenta_empresa_id_57322b76" ON "contabilidad_plancuenta" ("empresa_id");
ALTER TABLE "contabilidad_asientolinea" ADD CONSTRAINT "contabilidad_asiento_asiento_id_b378fb89_fk_contabili" FOREIGN KEY ("asiento_id") REFERENCES "contabilidad_asientocontable" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contabilidad_asientolinea" ADD CONSTRAINT "contabilidad_asiento_cuenta_id_91382447_fk_contabili" FOREIGN KEY ("cuenta_id") REFERENCES "contabilidad_plancuenta" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "contabilidad_asientolinea_asiento_id_b378fb89" ON "contabilidad_asientolinea" ("asiento_id");
CREATE INDEX "contabilidad_asientolinea_cuenta_id_91382447" ON "contabilidad_asientolinea" ("cuenta_id");
COMMIT;

-- === core.0002_perfil_usuario_sql ===
BEGIN;
--
-- Raw SQL operation
--

CREATE TABLE IF NOT EXISTS perfil_usuario (
    id                   BIGSERIAL PRIMARY KEY,
    user_id              INTEGER NOT NULL UNIQUE REFERENCES auth_user(id) ON DELETE CASCADE,
    empresa_id           INTEGER NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    sucursal_default_id  INTEGER REFERENCES sucursal(id) ON DELETE SET NULL,
    nombres              VARCHAR(120) NOT NULL DEFAULT '',
    apellido_paterno     VARCHAR(80) NOT NULL DEFAULT '',
    apellido_materno     VARCHAR(80) NOT NULL DEFAULT '',
    creado_en            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;

-- === core.0003_cliente_direccion ===
BEGIN;
--
-- Add field direccion to cliente
--
ALTER TABLE "cliente" ADD COLUMN "direccion" text DEFAULT '' NOT NULL;
ALTER TABLE "cliente" ALTER COLUMN "direccion" DROP DEFAULT;
COMMIT;

-- === core.0004_empresa_registro_aprobado ===
BEGIN;
--
-- Add field registro_aprobado to empresa
--
ALTER TABLE "empresa" ADD COLUMN "registro_aprobado" boolean DEFAULT true NOT NULL;
ALTER TABLE "empresa" ALTER COLUMN "registro_aprobado" DROP DEFAULT;
COMMIT;

-- === core.0005_notificacion_usuario ===
BEGIN;
--
-- Create model NotificacionUsuario
--
CREATE TABLE "notificacion_usuario" ("actualizado_en" timestamp with time zone NOT NULL, "creado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "titulo" varchar(200) NOT NULL, "mensaje" text NOT NULL, "leida" boolean NOT NULL, "categoria" varchar(40) NOT NULL, "user_id" integer NOT NULL);
ALTER TABLE "notificacion_usuario" ADD CONSTRAINT "notificacion_usuario_user_id_e16a34fe_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "notificacion_usuario_categoria_98e3fcb1" ON "notificacion_usuario" ("categoria");
CREATE INDEX "notificacion_usuario_categoria_98e3fcb1_like" ON "notificacion_usuario" ("categoria" varchar_pattern_ops);
CREATE INDEX "notificacion_usuario_user_id_e16a34fe" ON "notificacion_usuario" ("user_id");
COMMIT;

-- === core.0006_empresa_razon_social_help ===
BEGIN;
--
-- Alter field razon_social on empresa
--
-- (no-op)
COMMIT;

-- === core.0007_empresa_fecha_aprobacion ===
BEGIN;
--
-- Add field fecha_registro_aprobado to empresa
--
ALTER TABLE "empresa" ADD COLUMN "fecha_registro_aprobado" timestamp with time zone NULL;
COMMIT;

-- === core.0008_empresa_persona_natural_contacto ===
BEGIN;
--
-- Add field apellido_materno to empresa
--
ALTER TABLE "empresa" ADD COLUMN "apellido_materno" varchar(80) DEFAULT '' NOT NULL;
ALTER TABLE "empresa" ALTER COLUMN "apellido_materno" DROP DEFAULT;
--
-- Add field apellido_paterno to empresa
--
ALTER TABLE "empresa" ADD COLUMN "apellido_paterno" varchar(80) DEFAULT '' NOT NULL;
ALTER TABLE "empresa" ALTER COLUMN "apellido_paterno" DROP DEFAULT;
--
-- Add field nombres to empresa
--
ALTER TABLE "empresa" ADD COLUMN "nombres" varchar(120) DEFAULT '' NOT NULL;
ALTER TABLE "empresa" ALTER COLUMN "nombres" DROP DEFAULT;
--
-- Add field telefono_contacto to empresa
--
ALTER TABLE "empresa" ADD COLUMN "telefono_contacto" varchar(30) DEFAULT '' NOT NULL;
ALTER TABLE "empresa" ALTER COLUMN "telefono_contacto" DROP DEFAULT;
COMMIT;

-- === core.0009_vendedor_y_comprobante_campos ===
BEGIN;
--
-- Create model Vendedor
--
CREATE TABLE "vendedor" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "dni" varchar(20) NOT NULL, "apellido_paterno" varchar(80) NOT NULL, "apellido_materno" varchar(80) NOT NULL, "nombres" varchar(120) NOT NULL, "activo" boolean NOT NULL, "empresa_id" bigint NOT NULL, "sucursal_id" bigint NULL);
ALTER TABLE "vendedor" ADD CONSTRAINT "vendedor_empresa_id_18a363b3_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "vendedor" ADD CONSTRAINT "vendedor_sucursal_id_cf9698a7_fk_sucursal_id" FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "vendedor_dni_82811f92" ON "vendedor" ("dni");
CREATE INDEX "vendedor_dni_82811f92_like" ON "vendedor" ("dni" varchar_pattern_ops);
CREATE INDEX "vendedor_empresa_id_18a363b3" ON "vendedor" ("empresa_id");
CREATE INDEX "vendedor_sucursal_id_cf9698a7" ON "vendedor" ("sucursal_id");
COMMIT;

-- === inventario.0002_marca_y_item_marca ===
BEGIN;
--
-- Create model Marca
--
CREATE TABLE "inventario_marca" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar(120) NOT NULL, "activo" boolean NOT NULL, "empresa_id" bigint NOT NULL);
--
-- Add field marca to item
--
ALTER TABLE "inventario_item" ADD COLUMN "marca_id" bigint NULL CONSTRAINT "inventario_item_marca_id_45726290_fk_inventario_marca_id" REFERENCES "inventario_marca"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "inventario_item_marca_id_45726290_fk_inventario_marca_id" IMMEDIATE;
--
-- Create constraint uniq_marca_nombre_por_empresa on model marca
--
ALTER TABLE "inventario_marca" ADD CONSTRAINT "uniq_marca_nombre_por_empresa" UNIQUE ("empresa_id", "nombre");
ALTER TABLE "inventario_marca" ADD CONSTRAINT "inventario_marca_empresa_id_af7c825d_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventario_marca_empresa_id_af7c825d" ON "inventario_marca" ("empresa_id");
CREATE INDEX "inventario_item_marca_id_45726290" ON "inventario_item" ("marca_id");
COMMIT;

-- === inventario.0003_unidad_medida_item_fk ===
BEGIN;
--
-- Create model UnidadMedida
--
CREATE TABLE "inventario_unidadmedida" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "codigo" varchar(20) NOT NULL, "nombre" varchar(120) NOT NULL, "codigo_close2u" varchar(80) NOT NULL, "activo" boolean NOT NULL, "empresa_id" bigint NOT NULL);
--
-- Create constraint uniq_unidad_medida_codigo_por_empresa on model unidadmedida
--
ALTER TABLE "inventario_unidadmedida" ADD CONSTRAINT "uniq_unidad_medida_codigo_por_empresa" UNIQUE ("empresa_id", "codigo");
--
-- Add field unidad_medida_nueva to item
--
ALTER TABLE "inventario_item" ADD COLUMN "unidad_medida_nueva_id" bigint NULL CONSTRAINT "inventario_item_unidad_medida_nueva__1a9e382f_fk_inventari" REFERENCES "inventario_unidadmedida"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "inventario_item_unidad_medida_nueva__1a9e382f_fk_inventari" IMMEDIATE;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field unidad_medida from item
--
ALTER TABLE "inventario_item" DROP COLUMN "unidad_medida" CASCADE;
--
-- Rename field unidad_medida_nueva on item to unidad_medida
--
ALTER TABLE "inventario_item" RENAME COLUMN "unidad_medida_nueva_id" TO "unidad_medida_id";
--
-- Alter field unidad_medida on item
--
SET CONSTRAINTS "inventario_item_unidad_medida_id_693fd65d_fk_inventari" IMMEDIATE; ALTER TABLE "inventario_item" DROP CONSTRAINT "inventario_item_unidad_medida_id_693fd65d_fk_inventari";
ALTER TABLE "inventario_item" ALTER COLUMN "unidad_medida_id" SET NOT NULL;
ALTER TABLE "inventario_item" ADD CONSTRAINT "inventario_item_unidad_medida_id_693fd65d_fk_inventari" FOREIGN KEY ("unidad_medida_id") REFERENCES "inventario_unidadmedida" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "inventario_unidadmedida" ADD CONSTRAINT "inventario_unidadmedida_empresa_id_1a7666ac_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "inventario_unidadmedida_empresa_id_1a7666ac" ON "inventario_unidadmedida" ("empresa_id");
CREATE INDEX "inventario_item_unidad_medida_id_693fd65d" ON "inventario_item" ("unidad_medida_id");
COMMIT;

-- === inventario.0004_rename_unidadmedida_codigo_close2u_codigo_sunat ===
BEGIN;
--
-- Rename field codigo_close2u on unidadmedida to codigo_sunat
--
ALTER TABLE "inventario_unidadmedida" RENAME COLUMN "codigo_close2u" TO "codigo_sunat";
COMMIT;

-- === inventario.0005_categoria_activo ===
BEGIN;
--
-- Add field activo to categoria
--
ALTER TABLE "inventario_categoria" ADD COLUMN "activo" boolean DEFAULT true NOT NULL;
ALTER TABLE "inventario_categoria" ALTER COLUMN "activo" DROP DEFAULT;
COMMIT;

-- === inventario.0006_almacen_activo ===
BEGIN;
--
-- Add field activo to almacen
--
ALTER TABLE "inventario_almacen" ADD COLUMN "activo" boolean DEFAULT true NOT NULL;
ALTER TABLE "inventario_almacen" ALTER COLUMN "activo" DROP DEFAULT;
COMMIT;

-- === restaurante.0001_initial ===
BEGIN;
--
-- Create model Comanda
--
CREATE TABLE "restaurante_comanda" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "mesa" varchar(20) NOT NULL, "nota" varchar(255) NOT NULL, "sucursal_id" bigint NOT NULL);
--
-- Create model ComandaLinea
--
CREATE TABLE "restaurante_comandalinea" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "cantidad" numeric(18, 4) NOT NULL, "nota" text NOT NULL, "estado" varchar(20) NOT NULL, "comanda_id" bigint NOT NULL, "item_id" bigint NOT NULL);
ALTER TABLE "restaurante_comanda" ADD CONSTRAINT "restaurante_comanda_sucursal_id_abffc424_fk_sucursal_id" FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "restaurante_comanda_sucursal_id_abffc424" ON "restaurante_comanda" ("sucursal_id");
ALTER TABLE "restaurante_comandalinea" ADD CONSTRAINT "restaurante_comandal_comanda_id_2340bab6_fk_restauran" FOREIGN KEY ("comanda_id") REFERENCES "restaurante_comanda" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "restaurante_comandalinea" ADD CONSTRAINT "restaurante_comandalinea_item_id_c73fc5df_fk_inventario_item_id" FOREIGN KEY ("item_id") REFERENCES "inventario_item" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "restaurante_comandalinea_comanda_id_2340bab6" ON "restaurante_comandalinea" ("comanda_id");
CREATE INDEX "restaurante_comandalinea_item_id_c73fc5df" ON "restaurante_comandalinea" ("item_id");
COMMIT;

-- === sessions.0001_initial ===
BEGIN;
--
-- Create model Session
--
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL);
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
COMMIT;

-- === ventas.0001_initial ===
BEGIN;
--
-- Create model Cotizacion
--
CREATE TABLE "ventas_cotizacion" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "numero" varchar(30) NOT NULL, "fecha" date NOT NULL, "estado" varchar(20) NOT NULL, "total" numeric(18, 2) NOT NULL, "cliente_id" bigint NULL, "empresa_id" bigint NOT NULL);
--
-- Create model CotizacionLinea
--
CREATE TABLE "ventas_cotizacionlinea" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "cantidad" numeric(18, 4) NOT NULL, "precio_unit" numeric(18, 4) NOT NULL, "subtotal" numeric(18, 2) NOT NULL, "cotizacion_id" bigint NOT NULL, "item_id" bigint NOT NULL);
--
-- Create model DocumentoVenta
--
CREATE TABLE "ventas_documentoventa" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "tipo" varchar(30) NOT NULL, "serie" varchar(10) NOT NULL, "numero" varchar(20) NOT NULL, "fecha_emision" date NOT NULL, "estado" varchar(20) NOT NULL, "subtotal" numeric(18, 2) NOT NULL, "igv" numeric(18, 2) NOT NULL, "total" numeric(18, 2) NOT NULL, "cliente_id" bigint NULL, "empresa_id" bigint NOT NULL, "sucursal_id" bigint NULL);
--
-- Create model DocumentoVentaLinea
--
CREATE TABLE "ventas_documentoventalinea" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "cantidad" numeric(18, 4) NOT NULL, "precio_unit" numeric(18, 4) NOT NULL, "subtotal" numeric(18, 2) NOT NULL, "documento_id" bigint NOT NULL, "item_id" bigint NOT NULL);
--
-- Create model Pedido
--
CREATE TABLE "ventas_pedido" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "origen" varchar(20) NOT NULL, "estado" varchar(20) NOT NULL, "referencia_externa" varchar(80) NOT NULL, "cliente_id" bigint NULL, "empresa_id" bigint NOT NULL);
--
-- Create model PedidoLinea
--
CREATE TABLE "ventas_pedidolinea" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "cantidad" numeric(18, 4) NOT NULL, "precio_unit" numeric(18, 4) NULL, "item_id" bigint NOT NULL, "pedido_id" bigint NOT NULL);
--
-- Create constraint uniq_documento_venta_correlativo on model documentoventa
--
CREATE UNIQUE INDEX "uniq_documento_venta_correlativo" ON "ventas_documentoventa" ("empresa_id", "tipo", "serie", "numero") WHERE (NOT ("serie" = '') AND NOT ("numero" = ''));
ALTER TABLE "ventas_cotizacion" ADD CONSTRAINT "ventas_cotizacion_cliente_id_a9bd0e74_fk_cliente_id" FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ventas_cotizacion" ADD CONSTRAINT "ventas_cotizacion_empresa_id_6d6100a6_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ventas_cotizacion_cliente_id_a9bd0e74" ON "ventas_cotizacion" ("cliente_id");
CREATE INDEX "ventas_cotizacion_empresa_id_6d6100a6" ON "ventas_cotizacion" ("empresa_id");
ALTER TABLE "ventas_cotizacionlinea" ADD CONSTRAINT "ventas_cotizacionlin_cotizacion_id_382910cb_fk_ventas_co" FOREIGN KEY ("cotizacion_id") REFERENCES "ventas_cotizacion" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ventas_cotizacionlinea" ADD CONSTRAINT "ventas_cotizacionlinea_item_id_02e46698_fk_inventario_item_id" FOREIGN KEY ("item_id") REFERENCES "inventario_item" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ventas_cotizacionlinea_cotizacion_id_382910cb" ON "ventas_cotizacionlinea" ("cotizacion_id");
CREATE INDEX "ventas_cotizacionlinea_item_id_02e46698" ON "ventas_cotizacionlinea" ("item_id");
ALTER TABLE "ventas_documentoventa" ADD CONSTRAINT "ventas_documentoventa_cliente_id_0c5965cc_fk_cliente_id" FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ventas_documentoventa" ADD CONSTRAINT "ventas_documentoventa_empresa_id_96a1cd1d_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ventas_documentoventa" ADD CONSTRAINT "ventas_documentoventa_sucursal_id_f47d5a26_fk_sucursal_id" FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ventas_documentoventa_cliente_id_0c5965cc" ON "ventas_documentoventa" ("cliente_id");
CREATE INDEX "ventas_documentoventa_empresa_id_96a1cd1d" ON "ventas_documentoventa" ("empresa_id");
CREATE INDEX "ventas_documentoventa_sucursal_id_f47d5a26" ON "ventas_documentoventa" ("sucursal_id");
ALTER TABLE "ventas_documentoventalinea" ADD CONSTRAINT "ventas_documentovent_documento_id_6953b180_fk_ventas_do" FOREIGN KEY ("documento_id") REFERENCES "ventas_documentoventa" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ventas_documentoventalinea" ADD CONSTRAINT "ventas_documentovent_item_id_d4a2aa61_fk_inventari" FOREIGN KEY ("item_id") REFERENCES "inventario_item" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ventas_documentoventalinea_documento_id_6953b180" ON "ventas_documentoventalinea" ("documento_id");
CREATE INDEX "ventas_documentoventalinea_item_id_d4a2aa61" ON "ventas_documentoventalinea" ("item_id");
ALTER TABLE "ventas_pedido" ADD CONSTRAINT "ventas_pedido_cliente_id_a0af3b9c_fk_cliente_id" FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ventas_pedido" ADD CONSTRAINT "ventas_pedido_empresa_id_adff9f43_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ventas_pedido_cliente_id_a0af3b9c" ON "ventas_pedido" ("cliente_id");
CREATE INDEX "ventas_pedido_empresa_id_adff9f43" ON "ventas_pedido" ("empresa_id");
ALTER TABLE "ventas_pedidolinea" ADD CONSTRAINT "ventas_pedidolinea_item_id_e7a77e44_fk_inventario_item_id" FOREIGN KEY ("item_id") REFERENCES "inventario_item" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ventas_pedidolinea" ADD CONSTRAINT "ventas_pedidolinea_pedido_id_ab9c716a_fk_ventas_pedido_id" FOREIGN KEY ("pedido_id") REFERENCES "ventas_pedido" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "ventas_pedidolinea_item_id_e7a77e44" ON "ventas_pedidolinea" ("item_id");
CREATE INDEX "ventas_pedidolinea_pedido_id_ab9c716a" ON "ventas_pedidolinea" ("pedido_id");
COMMIT;

-- === tesoreria.0001_initial ===
BEGIN;
--
-- Create model Caja
--
CREATE TABLE "tesoreria_caja" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar(80) NOT NULL, "activa" boolean NOT NULL, "sucursal_id" bigint NOT NULL);
--
-- Create model Cobranza
--
CREATE TABLE "tesoreria_cobranza" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "monto_total" numeric(18, 2) NOT NULL, "monto_pagado" numeric(18, 2) NOT NULL, "fecha_vencimiento" date NULL, "estado" varchar(20) NOT NULL, "documento_venta_id" bigint NOT NULL, "empresa_id" bigint NOT NULL);
--
-- Create model CronogramaPago
--
CREATE TABLE "tesoreria_cronogramapago" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "descripcion" text NOT NULL, "monto" numeric(18, 2) NOT NULL, "fecha_vencimiento" date NOT NULL, "estado" varchar(20) NOT NULL, "empresa_id" bigint NOT NULL, "proveedor_id" bigint NULL);
--
-- Create model CuentaBancaria
--
CREATE TABLE "tesoreria_cuentabancaria" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "banco" varchar(100) NOT NULL, "numero" varchar(40) NOT NULL, "moneda" varchar(3) NOT NULL, "saldo" numeric(18, 2) NOT NULL, "activa" boolean NOT NULL, "empresa_id" bigint NOT NULL);
--
-- Create model PagoRecibido
--
CREATE TABLE "tesoreria_pagorecibido" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "monto" numeric(18, 2) NOT NULL, "metodo" varchar(30) NOT NULL, "caja_id" bigint NULL, "cobranza_id" bigint NULL, "cuenta_bancaria_id" bigint NULL, "empresa_id" bigint NOT NULL, "usuario_id" integer NULL);
--
-- Create model ConciliacionBancaria
--
CREATE TABLE "tesoreria_conciliacionbancaria" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "periodo" varchar(7) NOT NULL, "saldo_libro" numeric(18, 2) NULL, "saldo_banco" numeric(18, 2) NULL, "cerrada" boolean NOT NULL, "cuenta_id" bigint NOT NULL);
ALTER TABLE "tesoreria_caja" ADD CONSTRAINT "tesoreria_caja_sucursal_id_3405683b_fk_sucursal_id" FOREIGN KEY ("sucursal_id") REFERENCES "sucursal" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "tesoreria_caja_sucursal_id_3405683b" ON "tesoreria_caja" ("sucursal_id");
ALTER TABLE "tesoreria_cobranza" ADD CONSTRAINT "tesoreria_cobranza_documento_venta_id_97227924_fk_ventas_do" FOREIGN KEY ("documento_venta_id") REFERENCES "ventas_documentoventa" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tesoreria_cobranza" ADD CONSTRAINT "tesoreria_cobranza_empresa_id_6071cff7_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "tesoreria_cobranza_documento_venta_id_97227924" ON "tesoreria_cobranza" ("documento_venta_id");
CREATE INDEX "tesoreria_cobranza_empresa_id_6071cff7" ON "tesoreria_cobranza" ("empresa_id");
ALTER TABLE "tesoreria_cronogramapago" ADD CONSTRAINT "tesoreria_cronogramapago_empresa_id_38b4889f_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tesoreria_cronogramapago" ADD CONSTRAINT "tesoreria_cronogramapago_proveedor_id_39bbdd76_fk_proveedor_id" FOREIGN KEY ("proveedor_id") REFERENCES "proveedor" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "tesoreria_cronogramapago_empresa_id_38b4889f" ON "tesoreria_cronogramapago" ("empresa_id");
CREATE INDEX "tesoreria_cronogramapago_proveedor_id_39bbdd76" ON "tesoreria_cronogramapago" ("proveedor_id");
ALTER TABLE "tesoreria_cuentabancaria" ADD CONSTRAINT "tesoreria_cuentabancaria_empresa_id_72b139b8_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "tesoreria_cuentabancaria_empresa_id_72b139b8" ON "tesoreria_cuentabancaria" ("empresa_id");
ALTER TABLE "tesoreria_pagorecibido" ADD CONSTRAINT "tesoreria_pagorecibido_caja_id_809c9eee_fk_tesoreria_caja_id" FOREIGN KEY ("caja_id") REFERENCES "tesoreria_caja" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tesoreria_pagorecibido" ADD CONSTRAINT "tesoreria_pagorecibi_cobranza_id_083cacc9_fk_tesoreria" FOREIGN KEY ("cobranza_id") REFERENCES "tesoreria_cobranza" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tesoreria_pagorecibido" ADD CONSTRAINT "tesoreria_pagorecibi_cuenta_bancaria_id_5348a584_fk_tesoreria" FOREIGN KEY ("cuenta_bancaria_id") REFERENCES "tesoreria_cuentabancaria" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tesoreria_pagorecibido" ADD CONSTRAINT "tesoreria_pagorecibido_empresa_id_ecfe57a9_fk_empresa_id" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tesoreria_pagorecibido" ADD CONSTRAINT "tesoreria_pagorecibido_usuario_id_3af1d30c_fk_auth_user_id" FOREIGN KEY ("usuario_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "tesoreria_pagorecibido_caja_id_809c9eee" ON "tesoreria_pagorecibido" ("caja_id");
CREATE INDEX "tesoreria_pagorecibido_cobranza_id_083cacc9" ON "tesoreria_pagorecibido" ("cobranza_id");
CREATE INDEX "tesoreria_pagorecibido_cuenta_bancaria_id_5348a584" ON "tesoreria_pagorecibido" ("cuenta_bancaria_id");
CREATE INDEX "tesoreria_pagorecibido_empresa_id_ecfe57a9" ON "tesoreria_pagorecibido" ("empresa_id");
CREATE INDEX "tesoreria_pagorecibido_usuario_id_3af1d30c" ON "tesoreria_pagorecibido" ("usuario_id");
ALTER TABLE "tesoreria_conciliacionbancaria" ADD CONSTRAINT "tesoreria_conciliacionbancaria_cuenta_id_periodo_b03336e9_uniq" UNIQUE ("cuenta_id", "periodo");
ALTER TABLE "tesoreria_conciliacionbancaria" ADD CONSTRAINT "tesoreria_conciliaci_cuenta_id_b8ae5356_fk_tesoreria" FOREIGN KEY ("cuenta_id") REFERENCES "tesoreria_cuentabancaria" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "tesoreria_conciliacionbancaria_cuenta_id_b8ae5356" ON "tesoreria_conciliacionbancaria" ("cuenta_id");
COMMIT;

-- === tesoreria.0002_condicion_pago_tesoreria ===
BEGIN;
--
-- Add field documento_compra to cronogramapago
--
ALTER TABLE "tesoreria_cronogramapago" ADD COLUMN "documento_compra_id" bigint NULL CONSTRAINT "tesoreria_cronograma_documento_compra_id_202de33a_fk_compras_d" REFERENCES "compras_documentocompra"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "tesoreria_cronograma_documento_compra_id_202de33a_fk_compras_d" IMMEDIATE;
--
-- Alter field estado on cronogramapago
--
-- (no-op)
CREATE INDEX "tesoreria_cronogramapago_documento_compra_id_202de33a" ON "tesoreria_cronogramapago" ("documento_compra_id");
COMMIT;

-- === tesoreria.0003_pago_realizado_proveedor ===
BEGIN;
--
-- Change Meta options on cobranza
--
-- (no-op)
--
-- Create model PagoRealizadoProveedor
--
CREATE TABLE "tesoreria_pagorealizadoproveedor" ("creado_en" timestamp with time zone NOT NULL, "actualizado_en" timestamp with time zone NOT NULL, "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "monto" numeric(18, 2) NOT NULL, "metodo" varchar(30) NOT NULL, "cronograma_pago_id" bigint NOT NULL, "empresa_id" bigint NOT NULL, "usuario_id" integer NULL);
ALTER TABLE "tesoreria_pagorealizadoproveedor" ADD CONSTRAINT "tesoreria_pagorealiz_cronograma_pago_id_083d1b5e_fk_tesoreria" FOREIGN KEY ("cronograma_pago_id") REFERENCES "tesoreria_cronogramapago" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tesoreria_pagorealizadoproveedor" ADD CONSTRAINT "tesoreria_pagorealiz_empresa_id_537ec7ba_fk_empresa_i" FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tesoreria_pagorealizadoproveedor" ADD CONSTRAINT "tesoreria_pagorealiz_usuario_id_7acca299_fk_auth_user" FOREIGN KEY ("usuario_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "tesoreria_pagorealizadoproveedor_cronograma_pago_id_083d1b5e" ON "tesoreria_pagorealizadoproveedor" ("cronograma_pago_id");
CREATE INDEX "tesoreria_pagorealizadoproveedor_empresa_id_537ec7ba" ON "tesoreria_pagorealizadoproveedor" ("empresa_id");
CREATE INDEX "tesoreria_pagorealizadoproveedor_usuario_id_7acca299" ON "tesoreria_pagorealizadoproveedor" ("usuario_id");
COMMIT;

-- === ventas.0002_documentoventa_nubefact_enlace ===
BEGIN;
--
-- Add field nubefact_enlace to documentoventa
--
ALTER TABLE "ventas_documentoventa" ADD COLUMN "nubefact_enlace" varchar(512) DEFAULT '' NOT NULL;
ALTER TABLE "ventas_documentoventa" ALTER COLUMN "nubefact_enlace" DROP DEFAULT;
COMMIT;

-- === ventas.0003_documentoventa_observacion ===
BEGIN;
--
-- Add field observacion to documentoventa
--
ALTER TABLE "ventas_documentoventa" ADD COLUMN "observacion" text DEFAULT '' NOT NULL;
ALTER TABLE "ventas_documentoventa" ALTER COLUMN "observacion" DROP DEFAULT;
COMMIT;

-- === ventas.0004_vendedor_y_comprobante_campos ===
BEGIN;
--
-- Add field condicion_pago to documentoventa
--
ALTER TABLE "ventas_documentoventa" ADD COLUMN "condicion_pago" varchar(10) DEFAULT 'CONTADO' NOT NULL;
ALTER TABLE "ventas_documentoventa" ALTER COLUMN "condicion_pago" DROP DEFAULT;
--
-- Add field fecha_vencimiento to documentoventa
--
ALTER TABLE "ventas_documentoventa" ADD COLUMN "fecha_vencimiento" date NULL;
--
-- Add field medio_pago to documentoventa
--
ALTER TABLE "ventas_documentoventa" ADD COLUMN "medio_pago" varchar(24) DEFAULT '' NOT NULL;
ALTER TABLE "ventas_documentoventa" ALTER COLUMN "medio_pago" DROP DEFAULT;
--
-- Add field moneda to documentoventa
--
ALTER TABLE "ventas_documentoventa" ADD COLUMN "moneda" varchar(3) DEFAULT 'PEN' NOT NULL;
ALTER TABLE "ventas_documentoventa" ALTER COLUMN "moneda" DROP DEFAULT;
--
-- Add field precio_incluye_igv to documentoventa
--
ALTER TABLE "ventas_documentoventa" ADD COLUMN "precio_incluye_igv" boolean DEFAULT false NOT NULL;
ALTER TABLE "ventas_documentoventa" ALTER COLUMN "precio_incluye_igv" DROP DEFAULT;
--
-- Add field tipo_operacion to documentoventa
--
ALTER TABLE "ventas_documentoventa" ADD COLUMN "tipo_operacion" varchar(40) DEFAULT 'VENTA_INTERNA' NOT NULL;
ALTER TABLE "ventas_documentoventa" ALTER COLUMN "tipo_operacion" DROP DEFAULT;
--
-- Add field vendedor to documentoventa
--
ALTER TABLE "ventas_documentoventa" ADD COLUMN "vendedor_id" bigint NULL CONSTRAINT "ventas_documentoventa_vendedor_id_768821c2_fk_vendedor_id" REFERENCES "vendedor"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "ventas_documentoventa_vendedor_id_768821c2_fk_vendedor_id" IMMEDIATE;
CREATE INDEX "ventas_documentoventa_vendedor_id_768821c2" ON "ventas_documentoventa" ("vendedor_id");
COMMIT;

-- === ventas.0005_documento_sunat_nubefact ===
BEGIN;
--
-- Add field nubefact_sunat_codigo to documentoventa
--
ALTER TABLE "ventas_documentoventa" ADD COLUMN "nubefact_sunat_codigo" varchar(32) DEFAULT '' NOT NULL;
ALTER TABLE "ventas_documentoventa" ALTER COLUMN "nubefact_sunat_codigo" DROP DEFAULT;
--
-- Add field nubefact_sunat_descripcion to documentoventa
--
ALTER TABLE "ventas_documentoventa" ADD COLUMN "nubefact_sunat_descripcion" text DEFAULT '' NOT NULL;
ALTER TABLE "ventas_documentoventa" ALTER COLUMN "nubefact_sunat_descripcion" DROP DEFAULT;
COMMIT;

-- === ventas.0006_cotizacion_interna_y_origen_comprobante ===
BEGIN;
--
-- Add field condicion_pago to cotizacion
--
ALTER TABLE "ventas_cotizacion" ADD COLUMN "condicion_pago" varchar(10) DEFAULT 'CONTADO' NOT NULL;
ALTER TABLE "ventas_cotizacion" ALTER COLUMN "condicion_pago" DROP DEFAULT;
--
-- Add field correlativo to cotizacion
--
ALTER TABLE "ventas_cotizacion" ADD COLUMN "correlativo" integer NULL CHECK ("correlativo" >= 0);
--
-- Add field fecha_vencimiento to cotizacion
--
ALTER TABLE "ventas_cotizacion" ADD COLUMN "fecha_vencimiento" date NULL;
--
-- Add field igv to cotizacion
--
ALTER TABLE "ventas_cotizacion" ADD COLUMN "igv" numeric(18, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "ventas_cotizacion" ALTER COLUMN "igv" DROP DEFAULT;
--
-- Add field medio_pago to cotizacion
--
ALTER TABLE "ventas_cotizacion" ADD COLUMN "medio_pago" varchar(24) DEFAULT '' NOT NULL;
ALTER TABLE "ventas_cotizacion" ALTER COLUMN "medio_pago" DROP DEFAULT;
--
-- Add field moneda to cotizacion
--
ALTER TABLE "ventas_cotizacion" ADD COLUMN "moneda" varchar(3) DEFAULT 'PEN' NOT NULL;
ALTER TABLE "ventas_cotizacion" ALTER COLUMN "moneda" DROP DEFAULT;
--
-- Add field observacion to cotizacion
--
ALTER TABLE "ventas_cotizacion" ADD COLUMN "observacion" text DEFAULT '' NOT NULL;
ALTER TABLE "ventas_cotizacion" ALTER COLUMN "observacion" DROP DEFAULT;
--
-- Add field precio_incluye_igv to cotizacion
--
ALTER TABLE "ventas_cotizacion" ADD COLUMN "precio_incluye_igv" boolean DEFAULT false NOT NULL;
ALTER TABLE "ventas_cotizacion" ALTER COLUMN "precio_incluye_igv" DROP DEFAULT;
--
-- Add field serie to cotizacion
--
ALTER TABLE "ventas_cotizacion" ADD COLUMN "serie" varchar(10) DEFAULT '' NOT NULL;
ALTER TABLE "ventas_cotizacion" ALTER COLUMN "serie" DROP DEFAULT;
--
-- Add field subtotal to cotizacion
--
ALTER TABLE "ventas_cotizacion" ADD COLUMN "subtotal" numeric(18, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "ventas_cotizacion" ALTER COLUMN "subtotal" DROP DEFAULT;
--
-- Add field sucursal to cotizacion
--
ALTER TABLE "ventas_cotizacion" ADD COLUMN "sucursal_id" bigint NULL CONSTRAINT "ventas_cotizacion_sucursal_id_1851cf5a_fk_sucursal_id" REFERENCES "sucursal"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "ventas_cotizacion_sucursal_id_1851cf5a_fk_sucursal_id" IMMEDIATE;
--
-- Add field tipo_operacion to cotizacion
--
ALTER TABLE "ventas_cotizacion" ADD COLUMN "tipo_operacion" varchar(40) DEFAULT 'VENTA_INTERNA' NOT NULL;
ALTER TABLE "ventas_cotizacion" ALTER COLUMN "tipo_operacion" DROP DEFAULT;
--
-- Add field vendedor to cotizacion
--
ALTER TABLE "ventas_cotizacion" ADD COLUMN "vendedor_id" bigint NULL CONSTRAINT "ventas_cotizacion_vendedor_id_c8ff6a81_fk_vendedor_id" REFERENCES "vendedor"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "ventas_cotizacion_vendedor_id_c8ff6a81_fk_vendedor_id" IMMEDIATE;
--
-- Add field cotizacion_origen to documentoventa
--
ALTER TABLE "ventas_documentoventa" ADD COLUMN "cotizacion_origen_id" bigint NULL UNIQUE CONSTRAINT "ventas_documentovent_cotizacion_origen_id_c1fbbc4d_fk_ventas_co" REFERENCES "ventas_cotizacion"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "ventas_documentovent_cotizacion_origen_id_c1fbbc4d_fk_ventas_co" IMMEDIATE;
--
-- Alter field numero on cotizacion
--
ALTER TABLE "ventas_cotizacion" ALTER COLUMN "numero" TYPE varchar(20);
--
-- Create constraint uniq_cotizacion_correlativo on model cotizacion
--
CREATE UNIQUE INDEX "uniq_cotizacion_correlativo" ON "ventas_cotizacion" ("empresa_id", "serie", "correlativo") WHERE ("correlativo" IS NOT NULL AND NOT ("serie" = ''));
CREATE INDEX "ventas_cotizacion_sucursal_id_1851cf5a" ON "ventas_cotizacion" ("sucursal_id");
CREATE INDEX "ventas_cotizacion_vendedor_id_c8ff6a81" ON "ventas_cotizacion" ("vendedor_id");
COMMIT;

