-- =============================================================================
-- Duplicado dentro de: docs/sql/gestor_ventas_esquema_completo.sql (use ese archivo).
-- Gestor_Ventas — Tablas core que core.0001_initial NO crea en la BD.
-- Estado mínimo compatible con el resto de migraciones Django (administracion,
-- inventario, etc.). Después ejecute: python manage.py migrate
--
-- Orden: migraciones hasta core.0001 → ESTE SCRIPT → migrate (resto).
-- =============================================================================

BEGIN;

CREATE TABLE empresa (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    razon_social varchar(255) NOT NULL,
    ruc varchar(11) NOT NULL,
    activo boolean NOT NULL,
    creado_en timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX uniq_empresa_ruc_no_vacio ON empresa (ruc) WHERE NOT (ruc = '');

CREATE TABLE sucursal (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    empresa_id bigint NOT NULL,
    nombre varchar(120) NOT NULL,
    direccion text NOT NULL,
    activo boolean NOT NULL,
    CONSTRAINT sucursal_empresa_id_fk FOREIGN KEY (empresa_id)
        REFERENCES empresa (id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX sucursal_empresa_id_idx ON sucursal (empresa_id);

CREATE TABLE cliente (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    empresa_id bigint NOT NULL,
    razon_social varchar(255) NOT NULL,
    documento varchar(20) NOT NULL,
    email varchar(254) NOT NULL,
    telefono varchar(40) NOT NULL,
    activo boolean NOT NULL,
    CONSTRAINT cliente_empresa_id_fk FOREIGN KEY (empresa_id)
        REFERENCES empresa (id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX cliente_empresa_id_idx ON cliente (empresa_id);
CREATE INDEX cliente_documento_idx ON cliente (documento);

CREATE UNIQUE INDEX uniq_cliente_documento_por_empresa
    ON cliente (empresa_id, documento) WHERE NOT (documento = '');

CREATE TABLE proveedor (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    empresa_id bigint NOT NULL,
    razon_social varchar(255) NOT NULL,
    documento varchar(20) NOT NULL,
    activo boolean NOT NULL,
    CONSTRAINT proveedor_empresa_id_fk FOREIGN KEY (empresa_id)
        REFERENCES empresa (id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX proveedor_empresa_id_idx ON proveedor (empresa_id);
CREATE INDEX proveedor_documento_idx ON proveedor (documento);

COMMIT;
