-- =============================================================================
-- Esquema completo unificado: docs/sql/gestor_ventas_esquema_completo.sql
-- Referencia DBeaver / documentación: estado ACTUAL de tablas core (apps.core.models)
-- alineado al ORM. NO usar junto con `migrate` si ya aplicó migraciones: duplicaría columnas.
-- Útil para diagramar relaciones o comparar con la BD real (pg_dump).
-- =============================================================================

BEGIN;

CREATE TABLE empresa (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    razon_social varchar(255) NOT NULL,
    ruc varchar(11) NOT NULL,
    apellido_paterno varchar(80) NOT NULL,
    apellido_materno varchar(80) NOT NULL,
    nombres varchar(120) NOT NULL,
    telefono_contacto varchar(30) NOT NULL,
    activo boolean NOT NULL,
    registro_aprobado boolean NOT NULL,
    fecha_registro_aprobado timestamp with time zone NULL,
    creado_en timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX uniq_empresa_ruc_no_vacio ON empresa (ruc) WHERE NOT (ruc = '');

CREATE TABLE sucursal (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    empresa_id bigint NOT NULL,
    nombre varchar(120) NOT NULL,
    direccion text NOT NULL,
    activo boolean NOT NULL,
    CONSTRAINT sucursal_empresa_id_fk FOREIGN KEY (empresa_id)
        REFERENCES empresa (id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX sucursal_empresa_id_idx ON sucursal (empresa_id);

CREATE TABLE cliente (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    empresa_id bigint NOT NULL,
    razon_social varchar(255) NOT NULL,
    documento varchar(20) NOT NULL,
    email varchar(254) NOT NULL,
    direccion text NOT NULL,
    telefono varchar(40) NOT NULL,
    activo boolean NOT NULL,
    CONSTRAINT cliente_empresa_id_fk FOREIGN KEY (empresa_id)
        REFERENCES empresa (id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX cliente_empresa_id_idx ON cliente (empresa_id);
CREATE INDEX cliente_documento_idx ON cliente (documento);

CREATE UNIQUE INDEX uniq_cliente_documento_por_empresa
    ON cliente (empresa_id, documento) WHERE NOT (documento = '');

CREATE TABLE proveedor (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    empresa_id bigint NOT NULL,
    razon_social varchar(255) NOT NULL,
    documento varchar(20) NOT NULL,
    activo boolean NOT NULL,
    CONSTRAINT proveedor_empresa_id_fk FOREIGN KEY (empresa_id)
        REFERENCES empresa (id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX proveedor_empresa_id_idx ON proveedor (empresa_id);
CREATE INDEX proveedor_documento_idx ON proveedor (documento);

COMMIT;
