# Generated by Django 5.2.13 on 2026-04-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='registro_aprobado',
            field=models.BooleanField(default=True, help_text='False = registro web pendiente de aprobación por superusuario.'),
        ),
    ]
