# Generated by Django 5.2.13 on 2026-04-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notificacion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(help_text='Nombre mostrado del contribuyente: persona jurídica = razón social (RUC suele iniciar en 20); persona natural = nombre completo en padrón o el armado con el titular del registro.', max_length=255),
        ),
    ]
