# Generated by Django 5.2.13 on 2026-04-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empresa_razon_social_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fecha_registro_aprobado',
            field=models.DateTimeField(blank=True, help_text='Momento en que un superusuario aprobó el registro web (si aplica).', null=True),
        ),
    ]
