# Generated by Django 5.2.13 on 2026-04-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_empresa_fecha_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='apellido_materno',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='empresa',
            name='apellido_paterno',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombres',
            field=models.CharField(blank=True, default='', help_text='Nombres de pila del contribuyente (persona natural).', max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono_contacto',
            field=models.CharField(blank=True, default='', help_text='Teléfono para seguimiento comercial del registro / contacto principal.', max_length=30),
        ),
    ]
