# Generated by Django 5.2.13 on 2026-04-12 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empresa_persona_natural_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(blank=True, db_index=True, max_length=20)),
                ('apellido_paterno', models.CharField(blank=True, max_length=80)),
                ('apellido_materno', models.CharField(blank=True, max_length=80)),
                ('nombres', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='core.empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores', to='core.sucursal')),
            ],
            options={
                'db_table': 'vendedor',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
    ]
