# Generated by Django 5.2.13 on 2026-04-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_drop_restaurante_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo_comprobante',
            field=models.ImageField(blank=True, help_text='Logo en comprobantes (recomendado máx. 430×150 px; PNG o JPG).', null=True, upload_to='logos_comprobante/%Y/%m/'),
        ),
    ]
