# Generated by Django 5.2.13 on 2026-04-09 22:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('activa', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='core.sucursal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO_PARCIAL', 'Pagado parcial'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20)),
                ('documento_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobranzas', to='ventas.documentoventa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobranzas', to='core.empresa')),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CronogramaPago',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma_pagos', to='core.empresa')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cronograma_pagos', to='core.proveedor')),
            ],
            options={
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(blank=True, max_length=40)),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='core.empresa')),
            ],
            options={
                'verbose_name_plural': 'Cuentas bancarias',
            },
        ),
        migrations.CreateModel(
            name='PagoRecibido',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('metodo', models.CharField(max_length=30)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesoreria.caja')),
                ('cobranza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tesoreria.cobranza')),
                ('cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesoreria.cuentabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_recibidos', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('saldo_libro', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('saldo_banco', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cerrada', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='tesoreria.cuentabancaria')),
            ],
            options={
                'verbose_name_plural': 'Conciliaciones bancarias',
                'unique_together': {('cuenta', 'periodo')},
            },
        ),
    ]
