# Generated by Django 5.2.13 on 2026-04-12 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_condicion_pago_tesoreria'),
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramapago',
            name='documento_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cronograma_pagos', to='compras.documentocompra'),
        ),
        migrations.AlterField(
            model_name='cronogramapago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20),
        ),
    ]
