# Generated by Django 5.2.13 on 2026-04-12 07:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vendedor_y_comprobante_campos'),
        ('tesoreria', '0002_condicion_pago_tesoreria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobranza',
            options={'ordering': ['-creado_en', '-id']},
        ),
        migrations.CreateModel(
            name='PagoRealizadoProveedor',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('metodo', models.CharField(max_length=30)),
                ('cronograma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_registro', to='tesoreria.cronogramapago')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados_proveedor', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
