# Generated by Django 5.2.13 on 2026-04-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_almacen_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='direccion',
            field=models.TextField(blank=True, default='', help_text='Ubicación física o referencia del almacén (opcional).'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='codigo',
            field=models.CharField(help_text='Código corto interno (p. ej. UND, KG, PAR); puede abreviarse según la empresa.', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='codigo_sunat',
            field=models.CharField(blank=True, default='', help_text='Código oficial SUNAT Tabla 6 (p. ej. NIU, KGM, ZZ) para comprobantes electrónicos.', max_length=80, verbose_name='código SUNAT (Tabla 6)'),
        ),
    ]
