# Generated by Django 5.2.13 on 2026-04-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocompra',
            name='condicion_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10),
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Obligatoria si la compra es a crédito (genera obligación en tesorería).', null=True),
        ),
    ]
